// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB25scTjhF4ySMPaxoaRjZnZ44UfuCG-Z4',
    appId: '1:14568109363:web:bc377223c3726972ffba46',
    messagingSenderId: '14568109363',
    projectId: 'h-reed',
    authDomain: 'h-reed.firebaseapp.com',
    storageBucket: 'h-reed.firebasestorage.app',
    measurementId: 'G-BQ5Z8KB44B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnNMEKGiqmTwqaV2CI8tth93xDxS4Xgro',
    appId: '1:14568109363:android:c7c3f6d882fe6f53ffba46',
    messagingSenderId: '14568109363',
    projectId: 'h-reed',
    storageBucket: 'h-reed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQs1uzTo4K9TgioTfHhcUPV6InLdO5hb0',
    appId: '1:14568109363:ios:6f0c82b977f29eaeffba46',
    messagingSenderId: '14568109363',
    projectId: 'h-reed',
    storageBucket: 'h-reed.firebasestorage.app',
    iosBundleId: 'com.example.hReed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQs1uzTo4K9TgioTfHhcUPV6InLdO5hb0',
    appId: '1:14568109363:ios:6f0c82b977f29eaeffba46',
    messagingSenderId: '14568109363',
    projectId: 'h-reed',
    storageBucket: 'h-reed.firebasestorage.app',
    iosBundleId: 'com.example.hReed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB25scTjhF4ySMPaxoaRjZnZ44UfuCG-Z4',
    appId: '1:14568109363:web:1423ea90975765e5ffba46',
    messagingSenderId: '14568109363',
    projectId: 'h-reed',
    authDomain: 'h-reed.firebaseapp.com',
    storageBucket: 'h-reed.firebasestorage.app',
    measurementId: 'G-JLFK0D9VDH',
  );
}
